
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install roles from Ansible Galaxy
      shell: ansible-galaxy install {{ item }} 
      with_items:
        - geerlingguy.pip
        - geerlingguy.docker
        - geerlingguy.git

- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: netaddr

  tasks:
    - name: Install pip role
      include_role:
        name: geerlingguy.pip
