- name: docker playbook
  hosts: all
  become: yes
  become_method: sudo
  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose: true
    docker_compose_path: /usr/local/bin/docker-compose
    docker_users:
    - 'mike'

  roles:
    - geerlingguy.docker 
    
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Setup docker-prune cronjob
      copy:
        src: docker-prune
        dest: /etc/cron.weekly/docker-prune
        mode: 0755
  