- hosts: pxe
  become: yes
  become_method: sudo  

  tasks:
    - name: stop service systemd-resolved, if running
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
        daemon_reload: yes

    - stat:
        path: /etc/resolv.conf
      register: resolv

    - name: Remove symlink for /etc/resolv.conf
      when: resolv.stat.islnk is defined and resolv.stat.islnk
      file:
        path: /etc/resolv.conf
        state: absent

    - name: ensure file new /etc/resolv.conf exists
      copy:
        content: "nameserver 9.9.9.9"
        dest: /etc/resolv.conf
        force: no
        group: root
        owner: root
        mode: 0755

    - name: "Install dnsmasq/pxe packages and dependences"
      apt:
        pkg:
          - dnsmasq
          - ufw
          - net-tools
          - tftp
          - pxelinux
          - syslinux
          - p7zip-full
        state: present

    - set_fact:
        mask_cidr: "{{ ip | ipaddr('network/prefix') }}"
      vars:
        ip: "{{ ansible_eth1.ipv4.address }}/{{ ansible_eth1.ipv4.netmask }}"

    - name: Copy dnsmasq config
      template:
        src: pxe.conf
        dest: /etc/dnsmasq.d/pxe.conf
        group: root
        owner: root
        mode: 0755

    - name: Get username for current user
      command: whoami
      changed_when: false
      become: false
      register: id

    - name: Set a fact with the username.
      set_fact:
        current_user: "{{ id.stdout }}"  

    
       
    - name: Start dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
        enabled: yes
        daemon_reload: yes

        

     

    
