- name: include nginx docker playbook
  import_playbook: nginx.yml

- name: include pxe dnsmasq playbook
  import_playbook: dnsmasq.yml

# - name: include pxe ufw playbook
#   import_playbook: ufw.yml

- hosts: localhost
  become: true
  tasks:
  - name: disable ufw
    ufw:
      state: disabled
  
