- hosts: pxe
  tasks:
  - name: Generate random password for code_server 
    set_fact: 
      generated_pass: "{{lookup('password', '../../config/.dev_pass encrypt=sha512_crypt chars=ascii_letters,digits,hexdigits,punctuation')}}"

  - name: check directory exists
    stat:
      path: /apps/pxe
    register: dir_to_delete


  # - name: Stop docker-compose services
  #   docker_compose:
  #     project_src: /apps/pxe
  #     build: no
  #     stopped: yes
  #   become: false
  #   register: output
  #   when: "web.flask_web_1.state.running"

  # - name: Stop dcocker-compose services
  #   debug:
  #     var: output

  # collect stats about the dir
  
  - name: Creates nginx-config directory
    file:
      path: /apps/pxe/nginx-config
      state: directory

  - name: current local user id
    set_fact:
      current_puid: "{{ lookup('pipe', 'id -u') }}"
    failed_when: current_puid == ''

  - name: current local group id
    set_fact:
      current_pgid: "{{ lookup('pipe', 'id -g') }}"
    failed_when: current_pgid == ''
    
  - name: Create pxe docker-compose.yml
    template:
      src: docker-compose.yml.j2
      dest: /apps/pxe/docker-compose.yml
      mode: 0664

  - name: Create pxe Makefile
    template:
      src: Makefile.j2
      dest: /apps/pxe/Makefile
      mode: 0664

  - name: Create and start development services
    docker_compose:
      project_src: /apps/pxe
      state: present 
      restarted: yes
    register: output
    become: false
