- hosts: pxe
  become: yes
  become_method: sudo  
  tasks:
    - name: Generate random password for code_server 
      set_fact: 
        generated_pass: "{{lookup('password', '../../config/.dev_pass encrypt=sha512_crypt chars=ascii_letters,digits,hexdigits,punctuation')}}"

    - name: check directory exists
      stat:
        path: /apps/pxe/log
      register: dir_to_delete

    # delete directory if condition is true
    - name: Cleanup /apps/pxe directory
      file:
        state: absent
        path: /apps/pxe
      when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir

    - name: Create /apps/pxe/www/tftp/bios/pxelinux.cfg
      file:
        path: /apps/pxe/www/tftp/bios/pxelinux.cfg
        state: directory
        mode: 0755
      become: false

    - name: Copy pxelinux.cfg
      template:
        src: pxelinux.cfg.default.j2
        dest: /apps/pxe/www/tftp/bios/pxelinux.cfg/default
        mode: 0755
      become: false

    - name: copy pxelinux.0
      copy:
        src: /usr/lib/PXELINUX/pxelinux.0
        dest: /apps/pxe/www/tftp/bios/pxelinux.0
      become: false

    - name: copy syslinux modules
      shell: cp /usr/lib/syslinux/modules/bios/*.c32 /apps/pxe/www/tftp/bios
      become: false

    - name: Create /apps/pxe/www/tftp/cloud-init-bios
      file:
        path: /apps/pxe/www/tftp/cloud-init-bios
        state: directory
        mode: 0755
      become: false

    - name: Create pxe cloud-init meta-data file
      lineinfile:
        path: /apps/pxe/www/tftp/cloud-init-bios/meta-data
        line: "instance-id: focal-autoinstall"
        mode: 0664
        create: yes
      become: false

    - name: Create pxe cloud-init file
      template:
        src: cloud-init.j2
        dest: /apps/pxe/www/tftp/cloud-init-bios/user-data
        mode: 0664
      become: false

    # begin uefi booting setup with grub
    - name: Create /apps/pxe/www/tftp/grub
      file:
        path: /apps/pxe/www/tftp/grub/fonts
        state: directory
        mode: 0755
      become: false

    - name: Copy pxelinux.cfg
      template:
        src: grub.cfg.j2
        dest: /apps/pxe/www/tftp/grub/grub.cfg
        mode: 0755
      become: false

    - name: Copy shim.efi to grub directory
      shell: 
        cmd: cp /usr/lib/shim/shimx64.efi.signed /apps/pxe/www/tftp/bootx64.efi
        warn: false
        creates: /apps/pxe/www/tftp/bootx64.efi

    - name: Copy shim.efi to grub directory
      shell: 
        cmd: cp /usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed /apps/pxe/www/tftp/grubx64.efi
        warn: false
        creates: /apps/pxe/www/tftp/grubx64.efi

    - name: Copy unicode.pf2 to grub/fonts directory
      shell: 
        cmd: cp /usr/share/grub/unicode.pf2 /apps/pxe/www/tftp/grub/fonts/unicode.pf2 
        warn: false
        creates: /apps/pxe/www/tftp/unicode.pf2

    - name: Download ubuntu 20.04 server iso
      get_url:
        url: https://releases.ubuntu.com/20.04/ubuntu-20.04.1-live-server-amd64.iso
        dest: /apps/pxe/www/tftp/ubuntu-20.04.1-live-server-amd64.iso
        mode: 0644
      become: false

    - name: Create /tmp/ubuntu-20.04.1-live-server-amd64.iso/
      file:
        path: /tmp/ubuntu-20.04.1-live-server-amd64.iso/
        state: directory
        mode: 0755
      become: false

    - name: mount iso
      command: 
        cmd: mount /apps/pxe/www/tftp/ubuntu-20.04.1-live-server-amd64.iso /mnt
        creates: /mnt/boot 
        warn: false
      become: true

    - name: Copy {{item}} to bios directory
      copy:
        src: /mnt/casper/{{ item }}
        dest: /apps/pxe/www/tftp/bios/
      with_items:
        - vmlinuz
        - initrd

    - name: Copy {{item}} to grub directory
      copy:
        src: /mnt/casper/{{ item }}
        dest: /apps/pxe/www/tftp/grub/
      with_items:
        - vmlinuz
        - initrd

    - name: Copy kernel modules to grub directory
      shell: 
        cmd: cp -r /mnt/boot/grub/x86_64-efi /apps/pxe/www/tftp/grub
        warn: false

    - name: unmount iso
      command: 
        cmd: umount /mnt
        warn: false
      become: true
